// <auto-generated />
using System;
using HomeBase.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeBase.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319120000_AddComposeMetadataAndCategories")]
    partial class AddComposeMetadataAndCategories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeBase.API.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("Action").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Details").HasColumnType("text");
                    b.Property<string>("Target").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("Action");
                    b.HasIndex("CreatedAt");
                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("HomeBase.API.Models.ContainerState", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("ContainerName").IsRequired().HasColumnType("text");
                    b.Property<bool>("IsDisabled").HasColumnType("boolean");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("ContainerName").IsUnique();
                    b.ToTable("ContainerStates");
                });

            modelBuilder.Entity("HomeBase.API.Models.FirewallRule", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.Property<int>("Port").HasColumnType("integer");
                    b.Property<string>("Protocol").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("Port", "Protocol").IsUnique();
                    b.ToTable("FirewallRules");
                });

            modelBuilder.Entity("HomeBase.API.Models.Service", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("BuildContext").HasColumnType("text");
                    b.Property<int?>("CategoryId").HasColumnType("integer");
                    b.Property<string>("Color").IsRequired().HasColumnType("text");
                    b.Property<string>("ComposeName").HasColumnType("text");
                    b.Property<string>("ContainerName").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").IsRequired().HasColumnType("text");
                    b.Property<string>("EnvFile").HasColumnType("text");
                    b.Property<string>("Icon").IsRequired().HasColumnType("text");
                    b.Property<string>("Image").HasColumnType("text");
                    b.Property<bool>("IsAutoDiscovered").HasColumnType("boolean");
                    b.Property<bool>("IsEnabled").HasColumnType("boolean");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.Property<int?>("PreferPort").HasColumnType("integer");
                    b.Property<int>("SortOrder").HasColumnType("integer");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("UrlPath").HasColumnType("text");
                    b.HasKey("Id");
                    b.HasIndex("CategoryId");
                    b.HasIndex("ContainerName").IsUnique();
                    b.ToTable("Services");
                });

            modelBuilder.Entity("HomeBase.API.Models.ServiceCategory", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("Color").IsRequired().HasColumnType("text");
                    b.Property<string>("Icon").IsRequired().HasColumnType("text");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.Property<int>("SortOrder").HasColumnType("integer");
                    b.HasKey("Id");
                    b.ToTable("ServiceCategories");
                    b.HasData(
                        new { Id = 1, Name = "Media", Icon = "film", Color = "#e74c3c", SortOrder = 1 },
                        new { Id = 2, Name = "Development", Icon = "code", Color = "#3498db", SortOrder = 2 },
                        new { Id = 3, Name = "Monitoring", Icon = "activity", Color = "#10b981", SortOrder = 3 },
                        new { Id = 4, Name = "Productivity", Icon = "briefcase", Color = "#f59e0b", SortOrder = 4 },
                        new { Id = 5, Name = "Security", Icon = "shield", Color = "#ef4444", SortOrder = 5 },
                        new { Id = 6, Name = "AI/ML", Icon = "cpu", Color = "#8b5cf6", SortOrder = 6 },
                        new { Id = 7, Name = "Storage", Icon = "database", Color = "#06b6d4", SortOrder = 7 },
                        new { Id = 8, Name = "Networking", Icon = "globe", Color = "#f97316", SortOrder = 8 }
                    );
                });

            modelBuilder.Entity("HomeBase.API.Models.Setting", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("Description").HasColumnType("text");
                    b.Property<bool>("IsPortVariable").HasColumnType("boolean");
                    b.Property<bool>("IsSecret").HasColumnType("boolean");
                    b.Property<string>("Key").IsRequired().HasColumnType("text");
                    b.Property<string>("Section").IsRequired().HasColumnType("text");
                    b.Property<string>("ServiceComposeName").HasColumnType("text");
                    b.Property<int>("SortOrder").HasColumnType("integer");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Value").IsRequired().HasColumnType("text");
                    b.Property<int>("Version").HasColumnType("integer");
                    b.HasKey("Id");
                    b.HasIndex("Key").IsUnique();
                    b.ToTable("Settings");
                });

            modelBuilder.Entity("HomeBase.API.Models.SettingsHistory", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("ChangedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("NewValue").IsRequired().HasColumnType("text");
                    b.Property<string>("OldValue").HasColumnType("text");
                    b.Property<int>("SettingId").HasColumnType("integer");
                    b.HasKey("Id");
                    b.HasIndex("SettingId");
                    b.ToTable("SettingsHistory");
                });

            modelBuilder.Entity("HomeBase.API.Models.Service", b =>
                {
                    b.HasOne("HomeBase.API.Models.ServiceCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("Category");
                });

            modelBuilder.Entity("HomeBase.API.Models.SettingsHistory", b =>
                {
                    b.HasOne("HomeBase.API.Models.Setting", "Setting")
                        .WithMany()
                        .HasForeignKey("SettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Setting");
                });
#pragma warning restore 612, 618
        }
    }
}
